### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by huzhenjie** [TinkerPatch/tinkerpatch-sdk#15]
NullPointerException

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5364)
       at android.app.ActivityThread.-wrap2(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6077)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference
       at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:164)
       at com.alibaba.sdk.android.feedback.impl.FeedbackAPI.initToid(Unknown Source)
       at com.alibaba.sdk.android.feedback.impl.FeedbackAPI.basicInitProcess(Unknown Source)
       at com.alibaba.sdk.android.feedback.impl.FeedbackAPI.initAnnoy(Unknown Source)
       at com.scrat.test.TsApp.onCreate(Unknown Source)
       at com.tinkerpatch.sdk.loader.TinkerPatchReflectApplication.onCreate(Unknown Source)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5361)
       at android.app.ActivityThread.-wrap2(ActivityThread.java) 
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528) 
       at android.os.Handler.dispatchMessage(Handler.java:102) 
       at android.os.Looper.loop(Looper.java:154) 
       at android.app.ActivityThread.main(ActivityThread.java:6077) 
       at java.lang.reflect.Method.invoke(Native Method) 
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
```

**Comment by shwenzhang** [comment]
1. tinkerpatch版本
2. 机型
3. 能把启动开始的日志都打出来吗？

**Comment by huzhenjie** [comment]
大概知道什么原因了，我是用`reflectApplication = true`的情况，然后原来的Application里面获取`ApplicationContext`失败，就出现这个问题，换成`reflectApplication = false`的方式就没问题了。

麻烦说明一下`reflectApplication = true`的情况下，怎么获取ApplicationContext？

另：我觉得这个项目很有趣，请问是属于Tencent的还是个人团队开发的？

**Comment by simpleton** [comment]
@huzhenjie 因为一键接入的sdk，是对tinker整个项目的fat打包，所以如果接入一键接入就不要再引用任何tinker的依赖了。这里的反射有一些强依赖的东西，不能兼容老版本的tinker。如果使用 `reflectApplication = true`，建议按照tinkerpatch.com的文档做接入。

------

回答你的问题，这个sdk不是腾讯官方的，微信也没有使用这个sdk。只是觉得tinker的接入本身比较复杂就做了这个一键接入的sdk来帮助大家快速接入。
