### ISSUE TITLE
  java.util.UnknownFormatConversionException

### ISSUE THREAD

**Issue by TonyTangAndroid** [TinkerPatch/tinkerpatch-sdk#22]
我遇到了如下的问题。很是奇怪。

`     java.util.UnknownFormatConversionException: Conversion = '/'
                                                       at java.util.Formatter$FormatSpecifier.conversion(Formatter.java:2730)
                                                       at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2759)
                                                       at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2591)
                                                       at java.util.Formatter.parse(Formatter.java:2524)
                                                       at java.util.Formatter.format(Formatter.java:2472)
                                                       at java.util.Formatter.format(Formatter.java:2426)
                                                       at java.lang.String.format(String.java:2626)
                                                       at com.tencent.tinker.lib.util.TinkerLog$1.i(SourceFile:36)
                                                       at com.tencent.tinker.lib.util.TinkerLog.i(SourceFile:99)
                                                       at com.tinkerpatch.sdk.server.callback.TinkerPatchRequestCallback.onPatchSyncFail(SourceFile:218)
                                                       at com.tinkerpatch.sdk.server.a.a$1.a(SourceFile:159)
                                                       at com.tinkerpatch.sdk.server.a.a$2.a(SourceFile:208)
                                                       at com.tinkerpatch.sdk.server.c.a$1.a(SourceFile:65)
                                                       at com.tinkerpatch.sdk.server.c.a$a.run(SourceFile:136)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                       at java.lang.Thread.run(Thread.java:761)`

**Comment by TonyTangAndroid** [comment]
知道原因了，我在gradle.properties里配置了TINKER_PATCH_APP_KEY，然后使用括号印起来了，

`TINKER_PATCH_APP_KEY=“4d7869fddae8f27d”
`

事实是gradle 会自动把gradle.properties里的变量添加引号。所以我们自己不需要再加了。
