### ISSUE TITLE
MissingFormatArgumentException

### ISSUE THREAD

**Issue by bravolover520** [TinkerPatch/tinkerpatch-sdk#43]
java.util.MissingFormatArgumentException: Format specifier: 22d
                                                                      at java.util.Formatter.getArgument(Formatter.java:1111)
                                                                      at java.util.Formatter.doFormat(Formatter.java:1076)
                                                                      at java.util.Formatter.format(Formatter.java:1042)
                                                                      at java.util.Formatter.format(Formatter.java:1011)
                                                                      at java.lang.String.format(String.java:1999)
                                                                      at java.lang.String.format(String.java:1973)
                                                                      at com.tencent.tinker.lib.util.TinkerLog$1.w(TinkerLog.java:49)
                                                                      at com.tencent.tinker.lib.util.TinkerLog.w(TinkerLog.java:93)
                                                                      at com.tinkerpatch.sdk.server.callback.TinkerPatchRequestCallback.onPatchSyncFail(SourceFile:219)
                                                                      at com.tinkerpatch.sdk.server.a.a$1.onLoadFailed(SourceFile:200)
                                                                      at com.tinkerpatch.sdk.server.a.a$2.onLoadFailed(SourceFile:258)
                                                                      at com.tinkerpatch.sdk.server.b.a$1.onLoadFailed(SourceFile:65)
                                                                      at com.tinkerpatch.sdk.server.b.a$a.run(SourceFile:126)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                      at java.lang.Thread.run(Thread.java:841)

**Comment by simpleton** [comment]
麻烦问下使用的是什么版本？

**Comment by bravolover520** [comment]
1.1.7

**Comment by simpleton** [comment]
已fix在1.1.8
